Check static require in expressions
logdna/eslint-plugin-logdna pull request #7
Opened 2022-09-16 19:09 UTC by biblicalph

### What was done

Require file extension rule was using `VariableDeclaration` to identify require usage. This did not catch require usage in expressions.
This PR updates require check to use CallExpression - which covers both expression and assignment usage.

Ref: [Issue 6](https://github.com/logdna/eslint-plugin-logdna/issues/6)

2022-09-16 19:16 UTC, esatterwhite requested changes
For open source commits the issue trailer is `fixes:` and the issue id should be either `#id` or `gh-id`
so `fixes: #6`

2022-09-16 19:44 UTC, esatterwhite submitted a review, later dismissed

2022-09-16 19:47 UTC, esatterwhite approved these changes

2022-09-16 21:20 UTC, darinspivey approved these changes

2022-09-17 01:43 UTC, mdeltito approved these changes
awesome, thanks @biblicalph

2022-09-17 06:49 UTC, merged